live_config_reload = true

[bell]
duration = 0

[colors.cursor]
cursor = "#bbc2cf"
text = "#282c34"

[colors.normal]
black = "#282c34"
blue = "#51afef"
cyan = "#46d9ff"
green = "#98be65"
magenta = "#c678dd"
red = "#ff6c6b"
white = "#bbc2cf"
yellow = "#ecbe7b"

[colors.primary]
background = "#282c34"
foreground = "#bbc2cf"

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.bold]
style = "ExtraBold"

[font.bold_italic]
style = "ExtraBold Italic"

[font.italic]
style = "Medium Italic"

[font.normal]
family = "JetBrains Mono"
style = "Medium"

[font.offset]
x = 0
y = -5

[[key.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Alt|Control"

[[key.bindings]]
chars = "\u001B[97;6u"
key = "A"
mods = "Control|Shift"

[[key.bindings]]
chars = "\u001B[98;6u"
key = "B"
mods = "Control|Shift"

[[key.bindings]]
chars = "\u001B[99;6u"
key = "C"
mods = "Control|Shift"

[[key.bindings]]
chars = "\u001B[100;6u"
key = "D"
mods = "Control|Shift"

[[key.bindings]]
chars = "\u001B[101;6u"
key = "E"
mods = "Control|Shift"

[[key.bindings]]
chars = "\u001B[102;6u"
key = "F"
mods = "Control|Shift"

[[key.bindings]]
chars = "\u001B[103;6u"
key = "G"
mods = "Control|Shift"

[[key.bindings]]
chars = "\u001B[104;6u"
key = "H"
mods = "Control|Shift"

[[key.bindings]]
chars = "\u001B[105;6u"
key = "I"
mods = "Control|Shift"

[[key.bindings]]
chars = "\u001B[106;6u"
key = "J"
mods = "Control|Shift"

[[key.bindings]]
chars = "\u001B[107;6u"
key = "K"
mods = "Control|Shift"

[[key.bindings]]
chars = "\u001B[108;6u"
key = "L"
mods = "Control|Shift"

[[key.bindings]]
chars = "\u001B[109;6u"
key = "M"
mods = "Control|Shift"

[[key.bindings]]
chars = "\u001B[110;6u"
key = "N"
mods = "Control|Shift"

[[key.bindings]]
chars = "\u001B[111;6u"
key = "O"
mods = "Control|Shift"

[[key.bindings]]
chars = "\u001B[112;6u"
key = "P"
mods = "Control|Shift"

[[key.bindings]]
chars = "\u001B[113;6u"
key = "Q"
mods = "Control|Shift"

[[key.bindings]]
chars = "\u001B[114;6u"
key = "R"
mods = "Control|Shift"

[[key.bindings]]
chars = "\u001B[115;6u"
key = "S"
mods = "Control|Shift"

[[key.bindings]]
chars = "\u001B[116;6u"
key = "T"
mods = "Control|Shift"

[[key.bindings]]
chars = "\u001B[117;6u"
key = "U"
mods = "Control|Shift"

[[key.bindings]]
chars = "\u001B[118;6u"
key = "V"
mods = "Control|Shift"

[[key.bindings]]
chars = "\u001B[119;6u"
key = "W"
mods = "Control|Shift"

[[key.bindings]]
chars = "\u001B[120;6u"
key = "X"
mods = "Control|Shift"

[[key.bindings]]
chars = "\u001B[121;6u"
key = "Y"
mods = "Control|Shift"

[[key.bindings]]
chars = "\u001B[122;6u"
key = "Z"
mods = "Control|Shift"

[[key.bindings]]
chars = "\x17"
key = "Backspace"
mods = "Control"
#map ctrl+backspace send_text all \x17

[[key.bindings]]
chars = "\x17"
key = "Backspace"
mods = "Alt"

[[key.bindings]]
chars = "\x1b[33;2~"
key = "Backspace"
mods = "Shift"

[[key.bindings]]
chars = "\x1b[13;2u"
key = "Enter"
mods = "Shift"

#map ctrl+backspace send_text all \x17

allow_remote_control yes

macos_option_as_alt yes

# mapping
map alt+backspace send_text all \x17
map shift+backspace send_text all \x1b[33;2~
map shift+enter send_text all \x1b[13;2u


[mouse]
hide_when_typing = true

[scrolling]
history = 100000
multiplier = 5

# [shell]
# args = ["--login", "-c", "tmux attach || tmux"]
# program = "/usr/bin/zsh"

[window]
decorations = "none"
dynamic_padding = true
resize_increments = false
startup_mode = "Maximized"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 0
y = 0

[window.position]
x = 0
y = 0
