# ----- Basic Colors -----
foreground                      #bbc2cf
background                      #282c34
selection_foreground            none
selection_background            #3e6452

# ----- Cursor Colors -----
cursor                          #bbc2cf
cursor_text_color               #282c34

# ----- Window Border Colors -----
active_border_color             #46D9FF
inactive_border_color           #3f444a

# ----- Tab Bar Colors -----
active_tab_foreground           #282c34
active_tab_background           #DFDFDF
inactive_tab_foreground         #3f444a
inactive_tab_background         #5B6268

# ----- ANSI 16 Colors -----
# Black
# Normal Black
color0 #2a2e38
# Bright Black (Gray)
color8 #3f444a

# Red
# Normal Red
color1 #ff6c6b
# Bright Red
color9 #ff6655

# Green
# Normal Green
color2  #98be65
# Bright Green
color10 #99bb66

# Yellow
# Normal Yellow
color3  #ECBE7B
# Bright Yellow
color11 #ECBE7B

# Blue
# Normal Blue
color4  #51afef
# Bright Blue
color12 #51afef

# Magenta
# Normal Magenta
color5  #c678dd
# Bright Magenta
color13 #c678dd

# Cyan
# Normal Cyan
color6  #46D9FF
# Bright Cyan
color14 #46D9FF

# White
# Normal White (Light Gray)
color7  #DFDFDF
# Bright White (Foreground Color)
color15 #bbc2cf

