# ----- Basic Colors -----
foreground                      #cdd4e0
background                      #303541
selection_foreground            none
selection_background            #46546a

# ----- Cursor Colors -----
cursor                          #cdd4e0
cursor_text_color               #303541

# ----- Window Border Colors -----
active_border_color             #46D9FF
inactive_border_color           #434956

# ----- Tab Bar Colors -----
active_tab_foreground           #303541
active_tab_background           #e2e6ed
inactive_tab_foreground         #8b939f
inactive_tab_background         #5B6268

# ----- ANSI 16 Colors -----
# Black
# Normal Black
color0 #383e4a
# Bright Black (Gray)
color8 #636b7b

# Red
# Normal Red
color1 #ff6c6b
# Bright Red
color9 #ff7b72

# Green
# Normal Green
color2  #98be65
# Bright Green
color10 #abcf78

# Yellow
# Normal Yellow
color3  #ECBE7B
# Bright Yellow
color11 #f6d29b

# Blue
# Normal Blue
color4  #51afef
# Bright Blue
color12 #6dbbff

# Magenta
# Normal Magenta
color5  #c678dd
# Bright Magenta
color13 #d68fed

# Cyan
# Normal Cyan
color6  #46D9FF
# Bright Cyan
color14 #62e2ff

# White
# Normal White (Light Gray)
color7  #e5e9f0
# Bright White (Foreground Color)
color15 #f8f9fc

