#!/bin/bash

# Script to create symbolic links for config files to ~/.config/ and ~/

# Variables

# ask user for confirmation
# Step 1: Ensure Homebrew is installed
if ! command -v brew &>/dev/null; then
  echo "Homebrew not found. Installing Homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

echo >>$HOME/.zprofile
echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >>$HOME/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"

# Update Homebrew
echo "Updating Homebrew..."
brew update

echo "Installing command-line tools..."

brew install bat       # Clone of cat(1) with syntax highlighting
brew install colima    # Container runtimes on macOS
brew install coreutils # GNU File, Shell, and Text utilities
brew install curl      # Get a file from an HTTP, HTTPS, or FTP server
brew install docker    # Pack, ship, and run applications as containers
brew install fd        # Simple, fast alternative to find
# brew install fzf            # Command-line fuzzy finder
brew install gh         # GitHub command-line tool
brew install go         # Go programming language
brew install htop       # Improved top (interactive process viewer)
brew install jdtls      # Java language server protocol
brew install jp         # Terminal plots from JSON data
brew install jq         # Command-line JSON processor
brew install julia      # Fast, dynamic programming language
brew install jupyterlab # Interactive environments for code
brew install koekeishiya/formulae/skhd
brew install koekeishiya/formulae/yabai
brew install lf        # Terminal file manager
brew install luarocks  # Package manager for Lua
brew install neofetch  # System info script
brew install neovim    # Ambitious Vim-fork
brew install ollama    # Create, run, and share large language models
brew install openjdk   # Development kit for Java
brew install openssh   # OpenBSD SSH connectivity tools
brew install openssl   # Cryptography and SSL/TLS Toolkit
brew install pipx      # Execute binaries from Python packages
brew install python    # Python 3.11
brew install pyvim     # Pure Python Vim clone
brew install ripgrep   # Search tool like grep
brew install rust      # Safe, concurrent language
brew install syncthing # File synchronization application
brew install tldr      # Simplified man pages
brew install tmux      # Terminal multiplexer
brew install trash-cli # Command-line interface to trashcan
brew install tree      # Display directories as trees
brew install v2ray     # Platform for building proxies
brew install vim       # Vi 'workalike' with additional features
brew install wget      # Internet file retriever
brew install xray      # Platform for building proxies
brew install zoxide    # Shell extension for navigation
brew install yqrashawn/goku/goku
brew install direnv
brew install cmake
brew install cloc
brew install mactex

brew install deno
brew tap FelixKratz/formulae
brew install borders

brew install --cask font-jetbrains-mono-nerd-font

brew install font-lxgw-wenkai
brew install syncthing

brew install --cask syncthing # File synchronization application
brew install --cask skim
brew install --cask discord
brew install --cask zoom
brew install --cask obsidian
brew install --cask google-chrome
brew install --cask logi-options+
brew install --cask visual-studio-code
brew install --cask v2rayu
brew install --cask wechat
brew install --cask whatsapp
brew install --cask raycast
brew install --cask mos
brew install --cask betterdisplay
brew install --cask maccy
brew install --cask dropbox
brew install onedrive
brew install --cask marta
brew install --cask microsoft-outlook
brew install --cask microsoft-word
brew install --cask karabiner-elements
brew install pomdtr/tap/ray
brew install --cask google-drive

brew tap FelixKratz/formulae
brew install borders

sudo ln -s /Applications/Marta.app/Contents/Resources/launcher /usr/local/bin/marta

brew tap dimentium/autoraise
brew install autoraise --with-dexperimental_focus_first

echo ""

curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin installer=version-0.40.0
sudo ln -sf /Applications/kitty.app/Contents/MacOS/kitty /usr/local/bin/kitty

defaults write -g InitialKeyRepeat -int 10
defaults write -g KeyRepeat -int 1
