#!/usr/bin/env bash

# fzf edit recent file
open-recent-edit-file () {
  cwd=$(pwd)
  select_file=$(find . -type f -not -path '*/.*' -exec ls -lt1 -- {} + \
    | sed 's|^\./||' \
    | fzf --height 40% --reverse \
    --header="cwd=$cwd  | cmd='$EDITOR <file>'  ")
  if [ -z $select_file ]; then
    zle reset-prompt
    return
  fi
  [ ! -z $select_file ] && print -s $EDITOR $select_file ; $EDITOR $select_file
  [ ! -z $select_file ] && echo "$EDITOR $select_file"
  cd $cwd
  zle accept-line
}
zle -N open-recent-edit-file
bindkey '^f' open-recent-edit-file

open-recent-cd() {
  selected_dir=$(fd --type=d --exclude node_modules \
    | fzf --height 40% --reverse)
  if [ -z $selected_dir ]; then
    zle reset-prompt
    return
  fi
  cd $selected_dir

  zle accept-line
}

zle -N open-recent-cd
bindkey '^t' open-recent-cd

zoxide-jump () {
  # Assign the result of zoxide and fzf to a variable
  local dir="$(zoxide query --list | fzf --height 40% --reverse)"
  # Check if the directory string is non-empty
  if [[ -z "$dir" ]]; then
    # If it is empty, reset the prompt and return
    zle reset-prompt
    return
  fi
  if [[ -d "$dir" ]]; then
    # If the directory exists, change to it
    tmux new-window -c "$dir"
  else
    # If the directory does not exist, print an error message
    echo "Directory not found: $dir"
  fi
  zle accept-line
}
# autoload -U zoxide-jump
zle -N zoxide-jump
bindkey '^z' zoxide-jump

# tmux-sessionor
# In ~/.zshrc
# tmux-sessionor widget
# sessionor() {
#     if [[ -f $HOME/.config/zsh/bin/tmux-sessionizer ]]; then
#         $HOME/.config/zsh/bin/tmux-sessionizer
#         zle accept-line
#     else
#         echo "Error: tmux-sessionizer script not found"
#         return 1
#     fi
# }
# zle -N sessionor
# bindkey '^g' sessionor


