[[mgr.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on  = "K"
run = "plugin parent-arrow -1"

[[mgr.prepend_keymap]]
on  = "J"
run = "plugin parent-arrow 1"

# [[mgr.prepend_keymap]]
# on   = "<C-d>"
# run  = "plugin diff"
# desc = "Diff the selected with the hovered file"

# [[manager.prepend_keymap]]
# on = [ "1" ]
# run = "plugin relative-motions 1"
# desc = "Move in relative steps"
#
# [[manager.prepend_keymap]]
# on = [ "2" ]
# run = "plugin relative-motions 2"
# desc = "Move in relative steps"
#
# [[manager.prepend_keymap]]
# on = [ "3" ]
# run = "plugin relative-motions 3"
# desc = "Move in relative steps"
#
# [[manager.prepend_keymap]]
# on = [ "4" ]
# run = "plugin relative-motions 4"
# desc = "Move in relative steps"
#
# [[manager.prepend_keymap]]
# on = [ "5" ]
# run = "plugin relative-motions 5"
# desc = "Move in relative steps"
#
# [[manager.prepend_keymap]]
# on = [ "6" ]
# run = "plugin relative-motions 6"
# desc = "Move in relative steps"
#
# [[manager.prepend_keymap]]
# on = [ "7" ]
# run = "plugin relative-motions 7"
# desc = "Move in relative steps"
#
# [[manager.prepend_keymap]]
# on = [ "8" ]
# run = "plugin relative-motions 8"
# desc = "Move in relative steps"
#
# [[manager.prepend_keymap]]
# on = [ "9" ]
# run = "plugin relative-motions 9"
# desc = "Move in relative steps"
