#!/usr/bin/env bash

eval "$(fzf --zsh)"

export FZF_DEFAULT_COMMAND="fd --relative-path"
export FZF_DEFAULT_OPTS="--layout=reverse --bind \"ctrl-d:preview-half-page-down,ctrl-u:preview-half-page-up\""
export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS --history=$HOME/.fzf_history"
export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS --bind=ctrl-H:backward-kill-word"
export FZF_CTRL_H=1

# Using highlight (http://www.andre-simon.de/doku/highlight/en/highlight.html)
#export FZF_CTRL_T_OPTS="--preview '(highlight -O ansi -l {} 2> /dev/null || cat {} || tree -C {}) 2> /dev/null | head -200'"

bindkey '^T' fzf-completion
