#!/usr/bin/env zsh

# fzf edit recent file
open-recent-edit-file() {
  cwd=$(pwd)

  # exit if at $HOME
  if [[ $cwd == $HOME ]]; then
    echo "You are at home directory, exiting..."
    echo
    zle reset-prompt
    return
  fi

  select_file=$(
    if [[ "$(uname)" == "Linux" ]]; then
      fd --type=file --type=symlink \
        --strip-cwd-prefix -X stat -c "%Y %n" |
        sort -nr | cut -d' ' -f2- |
        fzf --height 40% --reverse -m --header="cwd=$cwd  | cmd='$EDITOR <file>'  "
      return
    fi
    if [[ "$(uname)" == "Darwin" ]]; then
      fd --type=file --type=symlink \
        --strip-cwd-prefix -X stat -f "%m %N" |
        sort -nr | cut -d' ' -f2- |
        fzf --height 40% --reverse -m --header="cwd=$cwd  | cmd='$EDITOR <file>'  "
      return
    fi
  )
  if [ -z $select_file ]; then
    zle reset-prompt
    return
  fi
  [ ! -z $select_file ] && print -s $EDITOR $select_file
  $EDITOR $select_file
  [ ! -z $select_file ] && echo "$EDITOR $select_file"
  cd $cwd
  zle accept-line
}
zle -N open-recent-edit-file
bindkey '^f' open-recent-edit-file
bindkey -M vicmd '^f' open-recent-edit-file
bindkey -M viins '^f' open-recent-edit-file

# open-recent-cd() {
#   selected_dir=$(fd --type=d --exclude node_modules |
#     fzf --height 40% --reverse)
#   if [ -z $selected_dir ]; then
#     zle reset-prompt
#     return
#   fi
#   cd $selected_dir
#
#   zle accept-line
# }
#
# zle -N open-recent-cd
# bindkey '^y' open-recent-cd
# bindkey -M vicmd '^y' open-recent-cd
# bindkey -M viins '^y' open-recent-cd

jump-to-dir-in-git-repo() {
  #
  if git rev-parse --is-inside-work-tree &>/dev/null; then
    cd $(git rev-parse --show-toplevel)
  fi

  if [[ "$(uname)" == "Linux" ]]; then
    selected_dir=$(fd --type=d --strip-cwd-prefix -X stat -c "%Y %n" | sort -nr | cut -d' ' -f2- | fzf --height 40% --reverse)
  fi
  if [[ "$(uname)" == "Darwin" ]]; then
    selected_dir=$(fd --type=d --strip-cwd-prefix -X stat -f "%m %N" | sort -nr | cut -d' ' -f2- | fzf --height 40% --reverse)
  fi
  if [ -z $selected_dir ]; then
    zle reset-prompt
    return
  fi
  cd $selected_dir

  zle accept-line
}
zle -N jump-to-dir-in-git-repo
bindkey '^g' jump-to-dir-in-git-repo
bindkey -M vicmd '^g' jump-to-dir-in-git-repo
bindkey -M viins '^g' jump-to-dir-in-git-repo

fzf-file-widget() {
  if [[ "$(uname)" == "Linux" ]]; then
    LBUFFER="${LBUFFER}$(fd --strip-cwd-prefix -X stat -c "%Y %n" | sort -nr | cut -d' ' -f2- | fzf --height 40% --reverse)"
    local ret=$?
    zle reset-prompt
    return $ret
  fi
  if [[ "$(uname)" == "Darwin" ]]; then
    LBUFFER="${LBUFFER}$(fd --strip-cwd-prefix -X stat -f "%m %N" | sort -nr | cut -d' ' -f2- | fzf --height 40% --reverse)"
    local ret=$?
    zle reset-prompt
    return $ret
  fi
}

zle -N fzf-file-widget
bindkey -M vicmd '^T' fzf-file-widget
bindkey -M viins '^T' fzf-file-widget

tmux-sessionizer-wrapper() {
  BUFFER="tmux-sessionizer"
  zle accept-line
}
zle -N tmux-sessionizer-wrapper
if [ -z "$TMUX" ]; then
  stty -ixon
  bindkey '^s' tmux-sessionizer-wrapper
  bindkey -M vicmd '^s' tmux-sessionizer-wrapper
  bindkey -M viins '^s' tmux-sessionizer-wrapper
fi


foreground() {
  BUFFER="fg"
  zle accept-line
}
zle -N foreground
if [ -z "$TMUX" ]; then
  bindkey '^z' foreground
  bindkey -M vicmd '^z' foreground
  bindkey -M viins '^z' foreground
fi


