#!/usr/bin/env zsh

# function yazicd() {
#   local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
#   yazi "$@" --cwd-file="$tmp"
#   IFS= read -r -d '' cwd <"$tmp"
#   [ -n "$cwd" ] && [ "$cwd" != "$PWD" ] && builtin cd -- "$cwd"
#   rm -f -- "$tmp"
# }
#
# alias y='yazicd'
# alias yazi='yazicd'
# alias lf='yazicd'
# alias f='yazicd'

alias lf="yazi"
alias y="yazi"
alias y="yazi"
