#!/usr/bin/env bash

note_dir="/home/so/git_repo/mine/note"

wiki_dir=$note_dir/wiki

tmux rename-window "note" 
cd $note_dir
clear

tmux new-window -n "wiki" -c $wiki_dir

tmux new-window -n "math" -c $note_dir/math

tmux select-window -t "note"

