#!/usr/bin/env bash

hugo_dir="/home/so/git_repo/mine/myblog"

blog_content="$hugo_dir/content"

tmux rename-window "test" 
cd $hugo_dir
clear

tmux new-window -n "post" -c $blog_content/post
tmux send-keys -t blog:2.1 "lf" enter

if [[ `echo $XDG_SESSION_TYPE` == "X11" ]]; then
  tmux new-window -n "keycast" -c $blog_content
  tmux send-keys -t blog:3.1 "screenkey --show-setting"
else
  tmux new-window -n "keycast" -c $blog_content
  tmux send-keys -t blog:3.1 "showmethekey-gtk"
fi

tmux new-window -n "gif" -c $blog_content
tmux send-keys -t blog:4.1 "peek"

tmux select-window -t "post"
