#!/usr/bin/env bash

nvim_dir="/home/so/.config/nvim"

tmux rename-window "nvim-dir" 
cd $nvim_dir
clear

tmux new-window -n "lua" -c "$nvim_dir/lua"

tmux new-window -n "plugins" -c "$nvim_dir/lua/plugins"

tmux new-window -n "vimL" -c "$nvim_dir/vimL"

tmux select-window -t "nvim"

