#!/usr/bin/env bash

set -euo pipefail

IGNORED_PATHS=(
  ~/tmp/*
  ~/projects/coder
)

INITIAL_DIRECTORIES=(
  ~/projects
  ~/projects/coder
  ~/projects/LSCM
  ~/projects/LSCM/CEDD
  ~/tmp
  ~/CUHK/year4
  ~/dotfiles

  # for testing
  ~/.asdflaksjfai
)

SEARCH_DIRECTORIES=()

for dir in "${INITIAL_DIRECTORIES[@]}"; do
  if [ -d "$dir" ]; then
    SEARCH_DIRECTORIES+=("$dir")
  fi
done

select_directory() {

  local exclusions=()
  for ignored_path in "${IGNORED_PATHS[@]}"; do
    exclusions+=("-not" "-path" "$ignored_path")
  done

  find "${SEARCH_DIRECTORIES[@]}" \
    -mindepth 0 -maxdepth 1 -type d \
    "${exclusions[@]}" \
    -not -path '*/.*' \
    -not -path '*/*.wt' \
    -exec ls -1dt {} + | uniq |
    fzf --height 100% -i --layout=default --header "Select a project directory"
}

create_or_connect_session() {
  local session_name="$1"
  local target_dir="$2"

  if ! pgrep tmux &>/dev/null; then
    tmux set-env -g BASE_DIR "$target_dir"
    tmux new-session -s "$session_name" -c "$target_dir"
    return
  fi

  if ! tmux has-session -t "$session_name" 2>/dev/null; then
    tmux set-env -g BASE_DIR "$target_dir"
    tmux new-session -ds "$session_name" -c "$target_dir"
  fi

  local temp_session_name="${session_name}_${RANDOM:2}"
  tmux set-env -g BASE_DIR "$target_dir"
  tmux new-session -d -t "$session_name" -s "$temp_session_name"

  if [[ -n "${TMUX-}" ]]; then
    tmux switch-client -t "$temp_session_name"
  else
    tmux attach-session -t "$temp_session_name"
  fi
}

main() {
  # start a tmux if not running without attach to the sesosin
  if ! pgrep tmux &>/dev/null; then
    tmux new-session -s "None" -d
  fi

  local selected_dir="${1-}"
  local session_name="${2-}"

  if [[ -z "$selected_dir" ]]; then
    selected_dir=$(select_directory)
    if [[ -z "$selected_dir" ]]; then
      echo "No directory selected. Exiting." >&2
      exit 1
    fi
  fi

  if [[ -z "$session_name" ]]; then
    session_name=$(basename "$selected_dir" | tr . _)
  fi

  create_or_connect_session "$session_name" "$selected_dir"
}

main "$@"
