#!/usr/bin/env bash

set -euo pipefail

IGNORED_PATHS=(
  ~/tmp/*
  ~/projects/coder
  ~/Obsidian/*
)

INITIAL_DIRECTORIES=(
  ~/Docker
  ~/projects
  ~/projects/coder
  ~/projects/LSCM
  ~/projects/LSCM/CEDD
  ~/tmp
  ~/CUHK/year4
  ~/dotfiles
  ~/Obsidian

  # for testing
  ~/.asdflaksjfai
)

SEARCH_DIRECTORIES=()

for dir in "${INITIAL_DIRECTORIES[@]}"; do
  if [ -d "$dir" ]; then
    SEARCH_DIRECTORIES+=("$dir")
  fi
done

select_directory() {

  local exclusions=()
  for ignored_path in "${IGNORED_PATHS[@]}"; do
    exclusions+=("-not" "-path" "$ignored_path")
  done

  find "${SEARCH_DIRECTORIES[@]}" \
    -mindepth 0 -maxdepth 1 -type d \
    "${exclusions[@]}" \
    -not -path '*/.*' \
    -not -path '*/*.wt' \
    -exec ls -1dt {} + | uniq |
    fzf --height 100% -i --layout=default --header "Select a project directory"
}

find_available_session_name() {
  local tag="$1"
  local index=1

  while tmux has-session -t "${tag}_${index}" 2>/dev/null; do
    ((index++))
  done
  echo "${tag}_${index}"
}

is_group_attached() {
  local group_name="$1"
  tmux list-sessions -F "#{session_group} #{session_attached}" 2>/dev/null | grep -q "^${group_name} 1"
}

create_or_connect_session() {
  # group name are unique for each session, a session can have multiple tags
  local group_name="$1"
  # target_dir is the directory to open in the tmux session
  local target_dir="$2"
  # tag is the session name show in tmux
  local tag="$3"

  if ! tmux has-session -t "$group_name" 2>/dev/null; then
    tmux set-environment -g BASE_DIR "$target_dir"
    tmux new-session -ds "$group_name" -c "$target_dir"
  fi

  local session_name
  session_name=$(find_available_session_name "$tag")
  tmux new-session -d -t "$group_name" -s "$session_name" -c "$target_dir"

  if is_group_attached "$group_name"; then
    tmux new-window -t "$session_name" -c "$target_dir"
  fi

  if [[ -n "${TMUX-}" ]]; then
    tmux switch-client -t "$session_name"
    return
  fi
  tmux attach-session -t "$session_name"
}

main() {
  # start a tmux if not running without attach to the sesosin
  if ! pgrep tmux &>/dev/null; then
    tmux new-session -s "None" -d
  fi

  local selected_dir
  selected_dir="${1-}"
  local session_name
  session_name="${2-}"

  if [[ -z "$selected_dir" ]]; then
    selected_dir=$(select_directory)
  fi

  [[ -z "$selected_dir" ]] && echo "No directory selected." >&2 && exit 1

  local group_name
  group_name=$(echo "$selected_dir" | tr . _)
  local tag
  tag="${session_name:-$(basename "$selected_dir" | tr . _)}"

  create_or_connect_session "$group_name" "$selected_dir" "$tag"
}

main "$@"
