return {
  {
    "kylechui/nvim-surround",
    keys = {
      { "gs",     mode = { "n", "v" } },
      { "ds",     mode = { "n", "v" } },
      { "cs",     mode = { "n", "v" } },
      -- { "<leader>~", mode = { "n", "v" }},
      -- { "<leader>*", mode = { "n", "v" }},
      -- { "<leader>$", mode = { "n", "v" }},
      -- { "<leader>`", mode = { "n", "v" }},
      -- { "<leader>>", mode = { "n", "v" }},
      -- { "<leader><", mode = { "n", "v" }},
      -- { "<leader>'", mode = { "n", "v" }},
      -- { "<leader>\"", mode = { "n", "v" }},
      -- { "<leader>}", mode = { "n", "v" }},
      -- { "<leader>{", mode = { "n", "v" }},
      -- { "<leader>]", mode = { "n", "v" }},
      -- { "<leader>[", mode = { "n", "v" }},
      -- { "<leader>)", mode = { "n", "v" }},
      { mode = "n", "<leader>(",      "<Plug>(nvim-surround-normal)iw(" },
      { mode = "n", "<leader>)",      "<Plug>(nvim-surround-normal)iw)" },
      { mode = "n", "<leader>[",      "<Plug>(nvim-surround-normal)iw[" },
      { mode = "n", "<leader>]",      "<Plug>(nvim-surround-normal)iw]" },
      { mode = "n", "<leader>{",      "<Plug>(nvim-surround-normal)iw{" },
      { mode = "n", "<leader>}",      "<Plug>(nvim-surround-normal)iw}" },
      { mode = "n", "<leader>\"",     "<Plug>(nvim-surround-normal)iw\"" },
      { mode = "n", "<leader>'",      "<Plug>(nvim-surround-normal)iw'" },
      { mode = "n", "<leader><",      "<Plug>(nvim-surround-normal)iw<" },
      { mode = "n", "<leader>>",      "<Plug>(nvim-surround-normal)iw>" },
      { mode = "n", "<leader>`",      "<Plug>(nvim-surround-normal)iw`" },
      { mode = "n", "<leader>$",      "<Plug>(nvim-surround-normal)iw$" },
      { mode = "n", "<leader>*",      "<Plug>(nvim-surround-normal)iw*" },
      { mode = "n", "<leader>~",      "<Plug>(nvim-surround-normal)iw~" },
      { mode = "v", "<leader>(",      "<Plug>(nvim-surround-visual)(" },
      { mode = "v", "<leader>)",      "<Plug>(nvim-surround-visual))" },
      { mode = "v", "<leader>[",      "<Plug>(nvim-surround-visual)[" },
      { mode = "v", "<leader>]",      "<Plug>(nvim-surround-visual)]" },
      { mode = "v", "<leader>{",      "<Plug>(nvim-surround-visual){" },
      { mode = "v", "<leader>}",      "<Plug>(nvim-surround-visual)}" },
      { mode = "v", "<leader>\"",     "<Plug>(nvim-surround-visual)\"" },
      { mode = "v", "<leader>'",      "<Plug>(nvim-surround-visual)'" },
      { mode = "v", "<leader><",      "<Plug>(nvim-surround-visual)<" },
      { mode = "v", "<leader>>",      "<Plug>(nvim-surround-visual)>" },
      { mode = "v", "<leader>`",      "<Plug>(nvim-surround-visual)`" },
      { mode = "v", "<leader>$",      "<Plug>(nvim-surround-visual)$" },
      { mode = "v", "<leader>*",      "<Plug>(nvim-surround-visual)*" },
      { mode = "v", "<leader>~",      "<Plug>(nvim-surround-visual)~" },
    },
    config = function()
      vim.cmd([[highlight default link NvimSurroundHighlight DiffChange]])
      require("nvim-surround").setup({
        keymaps = {
          insert = "<C-g>s",
          insert_line = "<C-g>S",
          normal = "gs",
          normal_cur = "gsw",
          normal_line = "gsl",
          normal_cur_line = "gsS",
          visual = "gs",
          visual_line = "gsl",
          delete = "ds",
          change = "cs",
        },
      })
    end
  }
}
