TMUX_CONF_DIR="${HOME}/.config/tmux"


source-file "${TMUX_CONF_DIR}/unbinds.conf"
source-file "${TMUX_CONF_DIR}/general_settings.conf"
source-file "${TMUX_CONF_DIR}/appearance.conf"
source-file "${TMUX_CONF_DIR}/prefix_bindings.conf"
source-file "${TMUX_CONF_DIR}/pane_bindings.conf"
source-file "${TMUX_CONF_DIR}/window_bindings.conf"
source-file "${TMUX_CONF_DIR}/session_bindings.conf"
source-file "${TMUX_CONF_DIR}/copymode_bindings.conf"
source-file "${TMUX_CONF_DIR}/mouse_settings.conf"
source-file "${TMUX_CONF_DIR}/default_keymaps.conf"

bind ^l run-shell "tmux unbind-key -a; tmux source-file ${TMUX_CONF_DIR}/tmux.conf" \; display-message "Config reloaded"
# source-file "${TMUX_CONF_DIR}/plugins.conf"

