#!/usr/bin/env bash

mkdir -p "$HOME/.local/bin"
mkdir -p "$HOME/projects/lscm/CEDD"

command_exists() {
  command -v "$1" >/dev/null 2>&1
}

detect_os_and_package_manager() {
  local os
  os=$(uname -s)

  if [ "$os" = "Darwin" ]; then
    OS="macos"
    if ! command_exists brew; then
      echo "Homebrew not found. Please install it first."
      exit 1
    fi
    PACKAGE_MANAGER="brew"
    return
  fi

  if [ "$os" = "Linux" ]; then
    OS="linux"
    if [ -f /etc/os-release ]; then
      # shellcheck source=/dev/null
      . /etc/os-release
      case "$ID" in
      ubuntu | debian)
        PACKAGE_MANAGER="apt"
        ;;
      arch)
        PACKAGE_MANAGER="pacman"
        ;;
      fedora)
        PACKAGE_MANAGER="dnf"
        ;;
      *)
        echo "Unsupported Linux distribution: $ID"
        exit 1
        ;;
      esac
    else
      echo "Unsupported Linux distribution."
      exit 1
    fi
    return
  fi

  echo "Unsupported OS: $os"
  exit 1
}

install_packages() {
  if [ -z "$PACKAGE_MANAGER" ]; then
    echo "Package manager not set."
    exit 1
  fi

  case "$PACKAGE_MANAGER" in
  brew)
    if ! command -v brew &>/dev/null; then
      echo "Homebrew not found. Installing Homebrew..."
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi

    echo >>$HOME/.zprofile
    echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >>$HOME/.zprofile
    eval "$(/opt/homebrew/bin/brew shellenv)"

    # Update Homebrew
    echo "Updating Homebrew..."
    brew install pipx neovim tmux bat zsh fd colima neofetch ripgrep python3-pip git
    brew install koekeishiya/formulae/skhd
    brew install koekeishiya/formulae/yabai
    brew install yqrashawn/goku/goku
    brew tap FelixKratz/formulae
    brew install borders
    brew install --cask font-jetbrains-mono-nerd-font
    brew install font-lxgw-wenkai
    brew install --cask syncthing
    brew install --cask skim
    brew install --cask discord
    brew install --cask zoom
    brew install --cask obsidian
    brew install --cask google-chrome
    brew install --cask logi-options+
    brew install --cask visual-studio-code
    brew install --cask v2rayu
    brew install --cask wechat
    brew install --cask whatsapp
    brew install --cask raycast
    brew install --cask mos
    brew install --cask betterdisplay
    brew install --cask maccy
    brew install --cask dropbox
    brew install onedrive
    brew install --cask microsoft-outlook
    brew install --cask microsoft-word
    brew install --cask karabiner-elements
    brew install pomdtr/tap/ray
    brew install --cask google-drive
    defaults write -g InitialKeyRepeat -int 10
    defaults write -g KeyRepeat -int 1
    curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin installer=version-0.40.0
    sudo ln -sf /Applications/kitty.app/Contents/MacOS/kitty /usr/local/bin/kitty
    curl -fsSL https://deno.land/install.sh | sh
    ;;
  apt)
    sudo apt-get install -y tmux neovim neofetch ripgrep tldr tree zoxide direnv pipx fd-find python3-pip zsh git --ignore-missing
    ln -sfv $(which fdfind) ~/.local/bin/fd
    curl -fsSL https://deno.land/install.sh | sh
    ;;
  dnf)
    sudo dnf install -y 'dnf-command(copr)'
    dnf copr enable pennbauman/ports
    sudo dnf install -y pipx neovim tmux bat zsh fd-find ripgrep htop tldr zoxide cloc python3-pip git lf --skip-unavailable
    curl -fsSL https://deno.land/install.sh | sh
    ;;
  esac
}

#### Main Script Execution Starts ####

echo "Download essential dependencies..."
detect_os_and_package_manager
install_packages

echo "Cloning the repository..."
if [ ! -d "dotfiles" ]; then
  git clone https://github.com/sokinpui/terminal_dotfiles.git dotfiles
fi
cd dotfiles

echo "Detected OS: $OS with package manager: $PACKAGE_MANAGER"

echo "Installation of dependencies complete!"

REPO_DIR="$(pwd)"
CONFIG_DIR="$HOME/.config"

echo "Repository directory: $REPO_DIR"
echo "Configuration directory: $CONFIG_DIR"

mkdir -p "$CONFIG_DIR"

echo "Creating symbolic links for configuration files..."

DOTFILES=(nvim AutoRaise tmux kitty bat lf skhd yabai)

for tool in "${DOTFILES[@]}"; do
  if [ -d "$REPO_DIR/$tool" ] || [ -f "$REPO_DIR/$tool" ]; then
    ln -sfv "$REPO_DIR/$tool" "$CONFIG_DIR/$tool"
  else
    echo "Warning: $tool not found in repository, skipping symlink."
  fi
done

echo "Symbolic linking complete! Please check the links and start your terminal tools."

ln -sfv "$REPO_DIR/zsh" "$CONFIG_DIR/zsh"

echo "Creating symbolic links for zsh configuration files..."
echo "Removing existing zsh configuration files..."
mv -f "$HOME/.zprofile" "$HOME/.zprofile.bak" 2>/dev/null || true
mv -f "$HOME/.zshrc" "$HOME/.zshrc.bak" 2>/dev/null || true
mv -f "$HOME/.zshenv" "$HOME/.zshenv.bak" 2>/dev/null || true

ln -sfv "$REPO_DIR/zsh/.zshrc" "$HOME/.zshrc"
ln -sfv "$REPO_DIR/zsh/.zshenv" "$HOME/.zshenv"
ln -sfv "$REPO_DIR/zsh/.zprofile" "$HOME/.zprofile"

pipx install neovim-remote
pipx install trash-cli
pip3 install pynvim --break-system-packages

ln -sfv "$REPO_DIR/gitignore_global" "$HOME/.gitignore_global"
git config --global core.excludesfile "$HOME/.gitignore_global"

mkdir -p "$HOME/.local"
ln -sfv "$REPO_DIR/scripts" "$HOME/.local/scripts"

go install github.com/sokinpui/wt-go/cmd/wtgo@latest
go install github.com/sokinpui/itf/cmd/itf@latest
go install github.com/sokinpui/pcat/cmd/pcat@latest
env CGO_ENABLED=0 go install -ldflags="-s -w" github.com/gokcehan/lf@latest

git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install

echo "Setup complete!"
