export MANPAGER='nvim +Man!'
export MANWIDTH=99

export EDITOR="nvim"
export SUDO_EDITOR="nvim"

export CARGOPATH="$HOME/.cargo"
export zsh_bin="$ZDOTDIR/bin"

export PIPX_HOME="$HOME/.local/pipx"
export TMUX_SESSIONIZER_META_PATH="$HOME/.local/scripts/tmux-sessionizer-meta"

# macOS only
if [[ "$(uname -s)" == "Darwin" ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"

  if [[ -n "$DBUS_LAUNCHD_SESSION_BUS_SOCKET" ]]; then
    export DBUS_SESSION_BUS_ADDRESS="unix:path=$DBUS_LAUNCHD_SESSION_BUS_SOCKET"
  fi

  export LDFLAGS="-L/opt/homebrew/opt/llvm/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/llvm/include"
  export HOMEBREW_NO_AUTO_UPDATE=1
  export JAVA_HOME=/opt/homebrew/opt/openjdk

  export YABAI_SWAP_NEXT=1
  export YABAI_AUTO_BALANCE="on"

  unset DOCKER_HOST
  docker context use orbstack &> /dev/null
  source ~/.orbstack/shell/init.zsh 2>/dev/null || :
fi
